### ISSUE TITLE
unable to pull song playing from certain WebApps

### ISSUE THREAD

**Issue by DiddleFiddle** [pendo324/universal-np#23]
U-NP fails to pull song info on some of the WebApps like the spotify web player, youtube music, google play, and pandora.
![iU1Eenl](https://user-images.githubusercontent.com/58942160/70909228-fc08fb00-1fda-11ea-8d8d-e7f148cf5ea2.png)

It's working fine for spotify desktop and youtube.com, but on the aforementioned players it shows "no song playing" even though the extension is showing the song name.

**Comment by blueprintChris** [comment]
I'm getting this issue. Any updates?

**Comment by FelipeRattu** [comment]
I'm having the same issue with Deezer

![image](https://user-images.githubusercontent.com/82958520/229639028-a989bc31-278b-4175-af90-b5a6fe130905.png)

Is the app still being supported?
