### ISSUE TITLE
Error getting info song from Spotify Windows

### ISSUE THREAD

**Issue by stevealexandre** [pendo324/universal-np#24]
Hi dude,

Your program doesn't have a signature certified by Windows which cause to need to be run in Administrator mode.
This administrator mode seems not being able to create the folder "data" required to store the file "nowplaying.txt". By creating it manually in "C:\Users\alexa\AppData\Roaming\universal-np", it's working but just give you info about this "bug" :).

**Comment by pendo324** [comment]
I think this is fixed in #29. I will probably create a new release sometime tomorrow (I'm in US Eastern time right now) and I'd appreciate it if you could test it out and let me know if it fixes your issue. I'll make a new comment here once the release is out.

**Comment by pendo324** [comment]
New release out now https://github.com/pendo324/universal-np/releases/tag/0.3.0
