### ISSUE TITLE
Google Play Music Desktop Player not supported

### ISSUE THREAD

**Issue by MySpl33n** [pendo324/universal-np#32]
I use GPMDP in YouTube Music mode. UNP doesn't have an option for it. I believe it is built using Electron. It puts pause in the status bar, the song name, and the artist name. It drops the pause status leaving the song name and artist name while playing.

**Comment by pendo324** [comment]
Hey, I added support for it in the latest update https://github.com/pendo324/universal-np/releases/tag/0.4.0

please check it out and let me know if it works for you

**Comment by MySpl33n** [comment]
It works, thank you very much! Seems to be some weird lag time when I switch between Google Play Music mode and YouTube Music mode but because I rarely do that, it doesn't matter to me.
