### ISSUE TITLE
Youtube Music support not working

### ISSUE THREAD

**Issue by uGuardian** [pendo324/universal-np#34]
The addon is perfectly capable of recognizing www.youtube.com, but doesn't appear to be recognizing music.google.com
The bottom right pop-up doesn't appear at all. Notably music.google.com doesn't even appear in the list of sites the extension has access to.

**Comment by xavieraiden** [comment]
Am also having this issue

**Comment by uGuardian** [comment]
...I mean, music.google.com isn't even valid anymore. It got shut down and merged into YouTube Music.
